import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { Spotlight } from "@/components/ui/spotlight";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
          <Spotlight
          className="-top-40 -z-50 left-0 md:left-60 md:-top-20"
          fill="white"
        />
        {children}
        <Toaster />
        

      </body>
    </html>
  );
}
